### ISSUE TITLE
HttpClientTransport#flush can call nil.downcase, raise NoMethodError

### ISSUE THREAD

**Issue by troy** [evernote/evernote-sdk-ruby#17]
FYI, in 1.25.1, I'm seeing [this line](https://github.com/evernote/evernote-sdk-ruby/blob/master/lib/thrift/transport/http_client_transport.rb#L59) occasionally call `nil.downcase` because `resp.content_type` is nil:

```
resp.content_type.downcase
```

Manifests as `NoMethodError: undefined method `downcase' for nil:NilClass`. I assume these are unsuccessful requests (timeouts, ..), but not so unsuccessful they should raise exceptions outside of the documented set.

**Comment by parov** [comment]
+1

**Comment by conch** [comment]
1.25.2 has @balser's fix for this issue and has just been uploaded to rubygems.org

**Comment by balser** [comment]
Thanks @conch! :+1:
