### ISSUE TITLE
regression error: findNotesMetadata with any:

### ISSUE THREAD

**Issue by drmarkpowell** [evernote/evernote-sdk-ruby#25]
When I run a findNotesMetadata with words set to "foo", it works.
However what I need to do is to set words to
 any: foo bar
...and have it return notes matching foo or bar
(I don't want foo AND bar (intersection), I want foo OR bar (union), to include either one of the words matched, or both.

This used to work great but lately it does not work as before...I get zero matches returned.
When I use any: keyword in the Evernote app, it works fine.
Please help!

**Comment by iafan** [comment]
`NoteFilter.words` field passed down to `findNotesMetadata` is expected to accept full search grammar, including the `any:` prefix. I recommend trying your `any: foo bar` search in Evernote Web, which uses the same API infrastructure. (Desktop Evernote clients implement search locally, so their results may be different.)

One difference between what you see when searching in Evernote Web and the actual query is that Evernote Web searches by word prefixes by modifying the query behind the scenes. If you search there for `any: foo bar` the actual query will be `any: foo* bar*` so that it will find all notes having words either starting with 'foo' or with 'bar'. If you want to search for exact words in Evernote Web, you need to search for `any: "foo" "bar"`, and the returned results should be equivalent to the `any: foo bar` or `any: "foo" "bar"` query done via `findNotesMetadata`.

So please compare the results with Evernote Web, and make sure you're accessing the same account on the same server (sandbox or production).

**Comment by drmarkpowell** [comment]
Sorry, I was not detailed enough in my explanation.

When I search with any: followed by 2 or more exact words surrounded by double quotes, such as
any: "02013" "02014"
where these exact words (albeit strings of digits) do appear exactly in the titles of one or more notes, I get zero notes returned. 
I also experience this when I try a search like:
any: "Sol 02013" "Sol 02014"
where again, these consecutive words appear in one or more notes. When I run the same query from Evernote Web, it works great.

Also I know my devtoken is working because I can create and remove notes just fine. Also I can run findNotesMetadata successfully and match whenever I do not use the any: keyword in the manner described.

**Comment by iafan** [comment]
Some quick sanity checks and questions:
1) Are you using the same accounts and the same server?
2) Do you have a personal or a business account? Could it be that you're, for example, searching in your personal notes when using `findNotesMetadata` (because devtokens are limited to personal notes only) but search in business notes when trying the same query in Evernote Web?

**Comment by drmarkpowell** [comment]
Definitely using the same account, where on web I'm logging in and with code I'm authenticating by dev token. No business account involved, strictly personal.
I swear this unmodified code that behaved properly in the past but has changed behavior now, but you're probably heard it all before and have good reason to be skeptical ;) Occam's razor, and all that. I really do hope that it's something simple. Let me know what other information I can provide to make this as easy as possible to diagnose?

**Comment by iafan** [comment]
I'd recommend trying to reproduce this on a simplest case possible: create a separate throwaway sandbox account with two notes with titles "A" and "B" respectively (and blank body). Search for `any: "A" "B"` in Evernote Web to make sure you're getting two notes. Then generate a devtoken for that account and use the minimal code to connect to that account and run the same query and display the number of notes found. This will help investigate the issue further.

Also, do you happen to remember when exactly it broke (which date)? This could also narrow down the possible causes if we are to have engineers investigate the issue.

**Comment by drmarkpowell** [comment]
Here is a standalone script that reproduces the problem:

```
require 'evernote-thrift'

def connect_to_evernote()
	begin
		userstoreUrl = "https://www.evernote.com/edam/user"
		userstoreTransport = Thrift::HTTPClientTransport.new(userstoreUrl)
		userstoreProtocol = Thrift::BinaryProtocol.new(userstoreTransport)
		userstore = Evernote::EDAM::UserStore::UserStore::Client.new(userstoreProtocol)
		user = "mslmars"
		userinfo = userstore.getPublicUserInfo(user)
		notestoreUrl = userinfo.noteStoreUrl()
		notestoreTransport = Thrift::HTTPClientTransport.new(notestoreUrl)
		notestoreProtocol = Thrift::BinaryProtocol.new(notestoreTransport)
		notestore = Evernote::EDAM::NoteStore::NoteStore::Client.new(notestoreProtocol)

		return userstore, notestore
	rescue Evernote::EDAM::Error::EDAMSystemException => ese
		puts "EDAMSystemException on findNotes: #{ese}, something went wrong retrieving notes."
		puts "errorcode #{ese.errorCode} message #{ese.message}"

	rescue Evernote::EDAM::Error::EDAMUserException => edue
		puts "EDAMUserException: #{edue}"
		puts "errorcode #{edue.errorCode} message #{edue.message}"
	end
end

(userstore, notestore) = connect_to_evernote()
spec = Evernote::EDAM::NoteStore::NotesMetadataResultSpec.new
spec.includeTitle = true

notebookGUID = "0296f732-694d-4ccd-9f5b-5983dc98b9e0"

filter = Evernote::EDAM::NoteStore::NoteFilter.new
filter.notebookGuid = notebookGUID

filter.words = 'Sol 02000'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 2000 notes.' % notelist.notes.length

filter.words = 'Sol 02001'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 2001 notes.' % notelist.notes.length

filter.words = 'any: "Sol 02000" "Sol 02001"'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 2000 or Sol 2001 notes.' % notelist.notes.length
```

The first two queries work correctly. I don't believe the third one does: it should return 40 results, but it returns 0 results.

Please correct me if I'm wrong, or if there is another alternative query that would do what this one intends to do, that's also good.

**Comment by iafan** [comment]
Thanks for providing the script. I'd still recommend running it on a separate sandbox account with just two notes as I suggested above. This is to ensure that there are no other factors involved and that the behavior is reproducible across both sandbox and production servers. This will also ensure that Evernote QA and Engineering can easily reproduce the test case by recreating an account and notes.

**Comment by drmarkpowell** [comment]
I can't create a public shared notebook from a sandbox account. The permissions will not allow for it.

Here is a production notebook that is publicly shared with only two notes in it. 
https://www.evernote.com/pub/drmarkpowell/evernotebugs

One has a title of
Sol 02000
the second note has a title of 
Sol 02001

When I query for either one individually, I get one result. When I query for any: and both titles, I get zero results.

```
require 'evernote-thrift'

def connect_to_evernote()
	begin
		userstoreUrl = "https://www.evernote.com/edam/user"
		userstoreTransport = Thrift::HTTPClientTransport.new(userstoreUrl)
		userstoreProtocol = Thrift::BinaryProtocol.new(userstoreTransport)
		userstore = Evernote::EDAM::UserStore::UserStore::Client.new(userstoreProtocol)
		user = "drmarkpowell"
		userinfo = userstore.getPublicUserInfo(user)
		notestoreUrl = userinfo.noteStoreUrl()
		notestoreTransport = Thrift::HTTPClientTransport.new(notestoreUrl)
		notestoreProtocol = Thrift::BinaryProtocol.new(notestoreTransport)
		notestore = Evernote::EDAM::NoteStore::NoteStore::Client.new(notestoreProtocol)

		return userstore, notestore
	rescue Evernote::EDAM::Error::EDAMSystemException => ese
		puts "EDAMSystemException on findNotes: #{ese}, something went wrong retrieving notes."
		puts "errorcode #{ese.errorCode} message #{ese.message}"

	rescue Evernote::EDAM::Error::EDAMUserException => edue
		puts "EDAMUserException: #{edue}"
		puts "errorcode #{edue.errorCode} message #{edue.message}"
	end
end

(userstore, notestore) = connect_to_evernote()
spec = Evernote::EDAM::NoteStore::NotesMetadataResultSpec.new
spec.includeTitle = true

notebookGUID = "fa278021-ce50-45f4-8fa8-e8175bac2f04"

filter = Evernote::EDAM::NoteStore::NoteFilter.new
filter.notebookGuid = notebookGUID

filter.words = 'Sol 02000'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 02000 notes.' % notelist.notes.length

filter.words = 'Sol 02001'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 02001 notes.' % notelist.notes.length

filter.words = 'any: "Sol 02000" "Sol 02001"'
notelist = notestore.findNotesMetadata("", filter, 0, 50, spec)
puts 'There are %d Sol 02000 or Sol 02001 notes.' % notelist.notes.length
```

**Comment by iafan** [comment]
Thanks Mark, I was able to reproduce the issue both with the API and using the web client, and filed an internal issue for further investigation.

**Comment by drmarkpowell** [comment]
That's great! Good to know that I wasn't mistaken...sorry I couldn't make it work from the sandbox.
Hopefully it's not a herculean task to fix. I look forward to this being resolved in the future.

**Comment by rezecib** [comment]
As a temporary workaround, it seems to work if you specify the notebook with `notebook:"Notebook Title"` instead of setting the notebook guid in the filter.

**Comment by rezecib** [comment]
This should be fixed now.

**Comment by drmarkpowell** [comment]
It is indeed! Thanks for the assist :)
